"""Neutral campaign-creation status and step vocabulary."""

CAMPAIGN_SAGA_NOT_STARTED = "NOT_STARTED"
CAMPAIGN_SAGA_IN_FLIGHT = "IN_FLIGHT"
CAMPAIGN_SAGA_APPLIED = "APPLIED"
CAMPAIGN_SAGA_ALREADY_PROCESSED = "ALREADY_PROCESSED"
CAMPAIGN_SAGA_UNKNOWN_RESULT = "UNKNOWN_RESULT"
CAMPAIGN_SAGA_FAILED = "FAILED"
CAMPAIGN_SAGA_PARTIALLY_APPLIED = "PARTIALLY_APPLIED"
CAMPAIGN_SAGA_COMPENSATION_REQUIRED = "COMPENSATION_REQUIRED"

CAMPAIGN_SAGA_STATE_VALUES = (
    CAMPAIGN_SAGA_NOT_STARTED,
    CAMPAIGN_SAGA_IN_FLIGHT,
    CAMPAIGN_SAGA_APPLIED,
    CAMPAIGN_SAGA_ALREADY_PROCESSED,
    CAMPAIGN_SAGA_UNKNOWN_RESULT,
    CAMPAIGN_SAGA_FAILED,
    CAMPAIGN_SAGA_PARTIALLY_APPLIED,
    CAMPAIGN_SAGA_COMPENSATION_REQUIRED,
)

CAMPAIGN_SAGA_PUBLIC_STATUS_VALUES = (
    CAMPAIGN_SAGA_APPLIED,
    CAMPAIGN_SAGA_ALREADY_PROCESSED,
    CAMPAIGN_SAGA_UNKNOWN_RESULT,
    CAMPAIGN_SAGA_FAILED,
    CAMPAIGN_SAGA_PARTIALLY_APPLIED,
    CAMPAIGN_SAGA_COMPENSATION_REQUIRED,
)

CAMPAIGN_CREATION_RESULT_STATUS_VALUES = (
    CAMPAIGN_SAGA_APPLIED,
    "NO_CHANGE",
    CAMPAIGN_SAGA_UNKNOWN_RESULT,
    CAMPAIGN_SAGA_PARTIALLY_APPLIED,
    CAMPAIGN_SAGA_COMPENSATION_REQUIRED,
    CAMPAIGN_SAGA_FAILED,
)

CAMPAIGN_STEP_CAMPAIGN_ADD = "CAMPAIGN_ADD"
CAMPAIGN_STEP_AD_GROUP_ADD = "AD_GROUP_ADD"
CAMPAIGN_STEP_ADS_ADD = "ADS_ADD"
CAMPAIGN_STEP_KEYWORD_ADD = "KEYWORD_ADD"
CAMPAIGN_STEP_MODERATION_SUBMIT = "MODERATION_SUBMIT"
CAMPAIGN_STEP_MODERATION_READBACK = "MODERATION_READBACK"
CAMPAIGN_STEP_CAMPAIGN_LAUNCH = "CAMPAIGN_LAUNCH"
CAMPAIGN_STEP_FULL_READBACK = "FULL_READBACK"

CAMPAIGN_SAGA_STEP_VALUES = (
    CAMPAIGN_STEP_CAMPAIGN_ADD,
    CAMPAIGN_STEP_AD_GROUP_ADD,
    CAMPAIGN_STEP_ADS_ADD,
    CAMPAIGN_STEP_KEYWORD_ADD,
    CAMPAIGN_STEP_MODERATION_SUBMIT,
    CAMPAIGN_STEP_MODERATION_READBACK,
    CAMPAIGN_STEP_CAMPAIGN_LAUNCH,
    CAMPAIGN_STEP_FULL_READBACK,
)

__all__ = [
    "CAMPAIGN_CREATION_RESULT_STATUS_VALUES",
    "CAMPAIGN_SAGA_ALREADY_PROCESSED",
    "CAMPAIGN_SAGA_APPLIED",
    "CAMPAIGN_SAGA_COMPENSATION_REQUIRED",
    "CAMPAIGN_SAGA_FAILED",
    "CAMPAIGN_SAGA_IN_FLIGHT",
    "CAMPAIGN_SAGA_NOT_STARTED",
    "CAMPAIGN_SAGA_PARTIALLY_APPLIED",
    "CAMPAIGN_SAGA_PUBLIC_STATUS_VALUES",
    "CAMPAIGN_SAGA_STATE_VALUES",
    "CAMPAIGN_SAGA_STEP_VALUES",
    "CAMPAIGN_SAGA_UNKNOWN_RESULT",
    "CAMPAIGN_STEP_ADS_ADD",
    "CAMPAIGN_STEP_AD_GROUP_ADD",
    "CAMPAIGN_STEP_CAMPAIGN_ADD",
    "CAMPAIGN_STEP_CAMPAIGN_LAUNCH",
    "CAMPAIGN_STEP_FULL_READBACK",
    "CAMPAIGN_STEP_KEYWORD_ADD",
    "CAMPAIGN_STEP_MODERATION_READBACK",
    "CAMPAIGN_STEP_MODERATION_SUBMIT",
]
